import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [name, setName] = useState('');
  return (
    <div className={styles.container}>
      <Head>
        <title>Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form method="post">
          <label htmlFor="inputName">Input name your pet</label>
          <input
            type="text"
            placeholder="name"
            id="inputName"
            onChange={(e) => {
              setName(e.target.value);
            }}
            value={name}
          />
          <button
            type="submit"
            onClick={(e) => {
              e.preventDefault();
              fetch('/api', {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify({ name: name }),
              });
            }}>
            Submit
          </button>
        </form>
      </main>
    </div>
  );
};

export default Home;
